"""create tables

Revision ID: dab49256035f
Revises: a3744172b942
Create Date: 2025-10-12 15:49:31.278344
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "dab49256035f"
down_revision = "a3744172b942"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "glossaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("locale_src", sa.String(length=10), nullable=False),
        sa.Column("locale_dst", sa.String(length=10), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "glossary_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("glossary_id", sa.Integer(), nullable=False),
        sa.Column("src", sa.String(length=400), nullable=False),
        sa.Column("dst", sa.String(length=400), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["glossary_id"],
            ["glossaries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("glossary_id", "src", name="uq_glossary_src"),
    )
    op.create_index(
        op.f("ix_glossary_terms_glossary_id"), "glossary_terms", ["glossary_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "processing", "done", "failed", name="job_status"),
            nullable=True,
        ),
        sa.Column("source_lang", sa.String(length=10), nullable=False),
        sa.Column("target_lang", sa.String(length=10), nullable=False),
        sa.Column("glossary_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["glossary_id"],
            ["glossaries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "job_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("input_path", sa.String(length=500), nullable=False),
        sa.Column("output_path", sa.String(length=500), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_files_job_id"), "job_files", ["job_id"], unique=False)
    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_metrics_job_id"), "metrics", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metrics_job_id"), table_name="metrics")
    op.drop_table("metrics")
    op.drop_index(op.f("ix_job_files_job_id"), table_name="job_files")
    op.drop_table("job_files")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_glossary_terms_glossary_id"), table_name="glossary_terms")
    op.drop_table("glossary_terms")
    op.drop_table("glossaries")
    op.drop_table("users")
    # ### end Alembic commands ###
